//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var MutableEphemeralStateService = require('./MutableEphemeralStateService')
var MutableEphemeralStateServiceClient = MutableEphemeralStateService.Client
var MutableEphemeralStateServiceProcessor = MutableEphemeralStateService.Processor
var ttypes = require('./bolt_types');
//HELPER FUNCTIONS AND STRUCTURES

BoltProxyService_registerRichStream_args = function(args) {
  this.r = null;
  if (args) {
    if (args.r !== undefined) {
      this.r = args.r;
    }
  }
};
BoltProxyService_registerRichStream_args.prototype = {};
BoltProxyService_registerRichStream_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.r = new ttypes.RichStream();
        this.r.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_registerRichStream_args.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_registerRichStream_args');
  if (this.r !== null && this.r !== undefined) {
    output.writeFieldBegin('r', Thrift.Type.STRUCT, 1);
    this.r.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_registerRichStream_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof ttypes.BoltError) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
BoltProxyService_registerRichStream_result.prototype = {};
BoltProxyService_registerRichStream_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.BoltError();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_registerRichStream_result.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_registerRichStream_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_deregisterRichStream_args = function(args) {
  this.r = null;
  if (args) {
    if (args.r !== undefined) {
      this.r = args.r;
    }
  }
};
BoltProxyService_deregisterRichStream_args.prototype = {};
BoltProxyService_deregisterRichStream_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.r = new ttypes.RichStream();
        this.r.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_deregisterRichStream_args.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_deregisterRichStream_args');
  if (this.r !== null && this.r !== undefined) {
    output.writeFieldBegin('r', Thrift.Type.STRUCT, 1);
    this.r.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_deregisterRichStream_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof ttypes.BoltError) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
BoltProxyService_deregisterRichStream_result.prototype = {};
BoltProxyService_deregisterRichStream_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.BoltError();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_deregisterRichStream_result.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_deregisterRichStream_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_dispatchRecords_args = function(args) {
  this.records = null;
  if (args) {
    if (args.records !== undefined) {
      this.records = args.records;
    }
  }
};
BoltProxyService_dispatchRecords_args.prototype = {};
BoltProxyService_dispatchRecords_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size118 = 0;
        var _rtmp3122;
        this.records = [];
        var _etype121 = 0;
        _rtmp3122 = input.readListBegin();
        _etype121 = _rtmp3122.etype;
        _size118 = _rtmp3122.size;
        for (var _i123 = 0; _i123 < _size118; ++_i123)
        {
          var elem124 = null;
          elem124 = new ttypes.Record();
          elem124.read(input);
          this.records.push(elem124);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_dispatchRecords_args.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_dispatchRecords_args');
  if (this.records !== null && this.records !== undefined) {
    output.writeFieldBegin('records', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRUCT, this.records.length);
    for (var iter125 in this.records)
    {
      if (this.records.hasOwnProperty(iter125))
      {
        iter125 = this.records[iter125];
        iter125.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_dispatchRecords_result = function(args) {
  this.e = null;
  if (args instanceof ttypes.BoltError) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
BoltProxyService_dispatchRecords_result.prototype = {};
BoltProxyService_dispatchRecords_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.BoltError();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_dispatchRecords_result.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_dispatchRecords_result');
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_updateSchedulerAddress_args = function(args) {
  this.e = null;
  if (args) {
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
BoltProxyService_updateSchedulerAddress_args.prototype = {};
BoltProxyService_updateSchedulerAddress_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.Endpoint();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_updateSchedulerAddress_args.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_updateSchedulerAddress_args');
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_updateSchedulerAddress_result = function(args) {
  this.e = null;
  if (args instanceof ttypes.BoltError) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
BoltProxyService_updateSchedulerAddress_result.prototype = {};
BoltProxyService_updateSchedulerAddress_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.BoltError();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_updateSchedulerAddress_result.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_updateSchedulerAddress_result');
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_registerWithScheduler_args = function(args) {
  this.meta = null;
  if (args) {
    if (args.meta !== undefined) {
      this.meta = args.meta;
    }
  }
};
BoltProxyService_registerWithScheduler_args.prototype = {};
BoltProxyService_registerWithScheduler_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.meta = new ttypes.ComputationMetadata();
        this.meta.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_registerWithScheduler_args.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_registerWithScheduler_args');
  if (this.meta !== null && this.meta !== undefined) {
    output.writeFieldBegin('meta', Thrift.Type.STRUCT, 1);
    this.meta.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyService_registerWithScheduler_result = function(args) {
};
BoltProxyService_registerWithScheduler_result.prototype = {};
BoltProxyService_registerWithScheduler_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BoltProxyService_registerWithScheduler_result.prototype.write = function(output) {
  output.writeStructBegin('BoltProxyService_registerWithScheduler_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BoltProxyServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(BoltProxyServiceClient, MutableEphemeralStateServiceClient);
BoltProxyServiceClient.prototype.seqid = function() { return this._seqid; }
BoltProxyServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
BoltProxyServiceClient.prototype.registerRichStream = function(r, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_registerRichStream(r);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_registerRichStream(r);
  }
};

BoltProxyServiceClient.prototype.send_registerRichStream = function(r) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('registerRichStream', Thrift.MessageType.CALL, this.seqid());
  var args = new BoltProxyService_registerRichStream_args();
  args.r = r;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BoltProxyServiceClient.prototype.recv_registerRichStream = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BoltProxyService_registerRichStream_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('registerRichStream failed: unknown result');
};
BoltProxyServiceClient.prototype.deregisterRichStream = function(r, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_deregisterRichStream(r);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_deregisterRichStream(r);
  }
};

BoltProxyServiceClient.prototype.send_deregisterRichStream = function(r) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('deregisterRichStream', Thrift.MessageType.CALL, this.seqid());
  var args = new BoltProxyService_deregisterRichStream_args();
  args.r = r;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BoltProxyServiceClient.prototype.recv_deregisterRichStream = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BoltProxyService_deregisterRichStream_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('deregisterRichStream failed: unknown result');
};
BoltProxyServiceClient.prototype.dispatchRecords = function(records, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_dispatchRecords(records);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_dispatchRecords(records);
  }
};

BoltProxyServiceClient.prototype.send_dispatchRecords = function(records) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('dispatchRecords', Thrift.MessageType.CALL, this.seqid());
  var args = new BoltProxyService_dispatchRecords_args();
  args.records = records;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BoltProxyServiceClient.prototype.recv_dispatchRecords = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BoltProxyService_dispatchRecords_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  callback(null)
};
BoltProxyServiceClient.prototype.updateSchedulerAddress = function(e, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_updateSchedulerAddress(e);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_updateSchedulerAddress(e);
  }
};

BoltProxyServiceClient.prototype.send_updateSchedulerAddress = function(e) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('updateSchedulerAddress', Thrift.MessageType.CALL, this.seqid());
  var args = new BoltProxyService_updateSchedulerAddress_args();
  args.e = e;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BoltProxyServiceClient.prototype.recv_updateSchedulerAddress = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BoltProxyService_updateSchedulerAddress_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  callback(null)
};
BoltProxyServiceClient.prototype.registerWithScheduler = function(meta, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_registerWithScheduler(meta);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_registerWithScheduler(meta);
  }
};

BoltProxyServiceClient.prototype.send_registerWithScheduler = function(meta) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('registerWithScheduler', Thrift.MessageType.ONEWAY, this.seqid());
  var args = new BoltProxyService_registerWithScheduler_args();
  args.meta = meta;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};
BoltProxyServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
Thrift.inherits(BoltProxyServiceProcessor, MutableEphemeralStateServiceProcessor)
BoltProxyServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

BoltProxyServiceProcessor.prototype.process_registerRichStream = function(seqid, input, output) {
  var args = new BoltProxyService_registerRichStream_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.registerRichStream.length === 1) {
    Q.fcall(this._handler.registerRichStream, args.r)
      .then(function(result) {
        var result = new BoltProxyService_registerRichStream_result({success: result});
        output.writeMessageBegin("registerRichStream", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BoltProxyService_registerRichStream_result(err);
        output.writeMessageBegin("registerRichStream", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.registerRichStream(args.r,  function (err, result) {
      var result = new BoltProxyService_registerRichStream_result((err != null ? err : {success: result}));
      output.writeMessageBegin("registerRichStream", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BoltProxyServiceProcessor.prototype.process_deregisterRichStream = function(seqid, input, output) {
  var args = new BoltProxyService_deregisterRichStream_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.deregisterRichStream.length === 1) {
    Q.fcall(this._handler.deregisterRichStream, args.r)
      .then(function(result) {
        var result = new BoltProxyService_deregisterRichStream_result({success: result});
        output.writeMessageBegin("deregisterRichStream", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BoltProxyService_deregisterRichStream_result(err);
        output.writeMessageBegin("deregisterRichStream", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.deregisterRichStream(args.r,  function (err, result) {
      var result = new BoltProxyService_deregisterRichStream_result((err != null ? err : {success: result}));
      output.writeMessageBegin("deregisterRichStream", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BoltProxyServiceProcessor.prototype.process_dispatchRecords = function(seqid, input, output) {
  var args = new BoltProxyService_dispatchRecords_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.dispatchRecords.length === 1) {
    Q.fcall(this._handler.dispatchRecords, args.records)
      .then(function(result) {
        var result = new BoltProxyService_dispatchRecords_result({success: result});
        output.writeMessageBegin("dispatchRecords", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BoltProxyService_dispatchRecords_result(err);
        output.writeMessageBegin("dispatchRecords", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.dispatchRecords(args.records,  function (err, result) {
      var result = new BoltProxyService_dispatchRecords_result((err != null ? err : {success: result}));
      output.writeMessageBegin("dispatchRecords", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BoltProxyServiceProcessor.prototype.process_updateSchedulerAddress = function(seqid, input, output) {
  var args = new BoltProxyService_updateSchedulerAddress_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.updateSchedulerAddress.length === 1) {
    Q.fcall(this._handler.updateSchedulerAddress, args.e)
      .then(function(result) {
        var result = new BoltProxyService_updateSchedulerAddress_result({success: result});
        output.writeMessageBegin("updateSchedulerAddress", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BoltProxyService_updateSchedulerAddress_result(err);
        output.writeMessageBegin("updateSchedulerAddress", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.updateSchedulerAddress(args.e,  function (err, result) {
      var result = new BoltProxyService_updateSchedulerAddress_result((err != null ? err : {success: result}));
      output.writeMessageBegin("updateSchedulerAddress", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BoltProxyServiceProcessor.prototype.process_registerWithScheduler = function(seqid, input, output) {
  var args = new BoltProxyService_registerWithScheduler_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.registerWithScheduler(args.meta)
}

