//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ComputationService = require('./ComputationService')
var ComputationServiceClient = ComputationService.Client
var ComputationServiceProcessor = ComputationService.Processor
var ttypes = require('./bolt_types');
//HELPER FUNCTIONS AND STRUCTURES

ComputationTestService_boltMetrics_args = function(args) {
};
ComputationTestService_boltMetrics_args.prototype = {};
ComputationTestService_boltMetrics_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ComputationTestService_boltMetrics_args.prototype.write = function(output) {
  output.writeStructBegin('ComputationTestService_boltMetrics_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ComputationTestService_boltMetrics_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof ttypes.BoltError) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
ComputationTestService_boltMetrics_result.prototype = {};
ComputationTestService_boltMetrics_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.MAP) {
        var _size108 = 0;
        var _rtmp3112;
        this.success = {};
        var _ktype109 = 0;
        var _vtype110 = 0;
        _rtmp3112 = input.readMapBegin();
        _ktype109 = _rtmp3112.ktype;
        _vtype110 = _rtmp3112.vtype;
        _size108 = _rtmp3112.size;
        for (var _i113 = 0; _i113 < _size108; ++_i113)
        {
          var key114 = null;
          var val115 = null;
          key114 = input.readString();
          val115 = input.readString();
          this.success[key114] = val115;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.BoltError();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ComputationTestService_boltMetrics_result.prototype.write = function(output) {
  output.writeStructBegin('ComputationTestService_boltMetrics_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.MAP, 0);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.success));
    for (var kiter116 in this.success)
    {
      if (this.success.hasOwnProperty(kiter116))
      {
        var viter117 = this.success[kiter116];
        output.writeString(kiter116);
        output.writeString(viter117);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ComputationTestServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(ComputationTestServiceClient, ComputationServiceClient);
ComputationTestServiceClient.prototype.seqid = function() { return this._seqid; }
ComputationTestServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
ComputationTestServiceClient.prototype.boltMetrics = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_boltMetrics();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_boltMetrics();
  }
};

ComputationTestServiceClient.prototype.send_boltMetrics = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('boltMetrics', Thrift.MessageType.CALL, this.seqid());
  var args = new ComputationTestService_boltMetrics_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ComputationTestServiceClient.prototype.recv_boltMetrics = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ComputationTestService_boltMetrics_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('boltMetrics failed: unknown result');
};
ComputationTestServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
Thrift.inherits(ComputationTestServiceProcessor, ComputationServiceProcessor)
ComputationTestServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ComputationTestServiceProcessor.prototype.process_boltMetrics = function(seqid, input, output) {
  var args = new ComputationTestService_boltMetrics_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.boltMetrics.length === 0) {
    Q.fcall(this._handler.boltMetrics)
      .then(function(result) {
        var result = new ComputationTestService_boltMetrics_result({success: result});
        output.writeMessageBegin("boltMetrics", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ComputationTestService_boltMetrics_result(err);
        output.writeMessageBegin("boltMetrics", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.boltMetrics( function (err, result) {
      var result = new ComputationTestService_boltMetrics_result((err != null ? err : {success: result}));
      output.writeMessageBegin("boltMetrics", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

